- name: Update APT cache
  apt: update_cache=yes
- name: Install required APT packages
  apt: name={{ item }} state=latest
  with_items:
    - nginx
    - python
    - python-dev
    - libpq-dev
    - libffi-dev
    - python-pip
    - postgresql
    - git

- name: Install required PIP packages
  pip: name={{ item }} state=latest
  with_items:
    - flask
    - flask-sqlalchemy
    - flask-socketio
    - psycopg2
    - requests
    - bcrypt
    - alembic
    - gunicorn
    - eventlet
    - flask-assets
    - cssmin
    - jsmin

- name: Remove default nginx virtual host
  file: name=/etc/nginx/sites-enabled/default state=absent
- name: Copy nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0660
- name: Copy nginx vhost
  copy: src=bronytv.conf dest=/etc/nginx/sites-enabled/bronytv owner=root group=root mode=0660
- name: Copy gunicorn service
  copy: src=btv-gunicorn.service dest=/etc/systemd/system/btv-gunicorn.service owner=root group=root mode=0660
- name: Create website directory
  file: name=/var/www/bronytv state=directory owner=www-data group=www-data mode=0770

- name: Create SSL directory
  file: name=/etc/nginx/certs state=directory owner=root group=root mode=0770
- name: Copy SSL DH params
  copy: src=private/dh.pem dest=/etc/nginx/certs/dh.pem owner=root group=root mode=0660

- name: Deploy website
  git: clone=yes repo=https://github.com/BronyTV/bronytv.net.git dest=/var/www/bronytv
  become_user: www-data
  become: yes
- name: Run Alembic migrations
  command: /usr/local/bin/alembic upgrade head chdir=/var/www/bronytv 

- name: Reload services
  systemd: daemon_reload=yes
- name: Enable gunicorn
  systemd: name=btv-gunicorn.service enabled=yes state=restarted
- name: Restart nginx
  service: name=nginx enabled=yes state=restarted

